const SET_READING = 'SET_READING';
const POST_READING = 'POST_READING';
const FETCH_READINGS = 'FETCH_READINGS';
const CLEAR_READING = 'CLEAR_READING';

export {SET_READING, POST_READING, FETCH_READINGS, CLEAR_READING};
